In [27]:
import numpy as np

a = np.arange(12)

a = a.reshape(3, 4)
print(a, "\n")
print(a.shape, "\n")
print(a.ndim, "\n")
print(a.size, "\n")
print(a.dtype, "\n")
print(a > 9, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

(3, 4) 

2 

12 

int64 

[[False False False False]
 [False False False False]
 [False False  True  True]] 



In [26]:
import numpy as np

a = np.zeros((3, 2))
b = np.ones((3, 2))
c = np.full((3, 2), 7)
print(a, "\n")
print(b, "\n")
print(c, "\n")

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]
 [7 7]] 



In [25]:
import numpy as np

a = np.array([10, 20, 30, 40]).reshape(2, 2)
b = np.arange(4).reshape(2, 2)

print(a, "\n")
print(b, "\n\n")
print(a + b, "\n")
print(a - b, "\n")
print(a * b, "\n")
print(a @ b, "\n")
print(b / a)

[[10 20]
 [30 40]] 

[[0 1]
 [2 3]] 


[[10 21]
 [32 43]] 

[[10 19]
 [28 37]] 

[[  0  20]
 [ 60 120]] 

[[ 40  70]
 [ 80 150]] 

[[0.         0.05      ]
 [0.06666667 0.075     ]]
